### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by PromzzyKoncepts** [PraisesPJMT/Best-Webdev-Practice#3]
# Great Job implementing the functions and functionalities required for the project
> Here are some issues we found in your code.

- Based on User experience, a task when tried to be edited, gets highlighted and the highlighted task does not disappear after clicking on another task, please add a function that removes a highlight on a task when the user leaves the selected task
- Your project seems to be missing a license file like the `MIT.md` file, please add it and edit your details to match the current project
- When a user adds multiple tasks say 15+ tasks and chooses to delete them for reasons of irrelevancy or repetition, the user will have to mark them one by one before deleting, Thereby taking longer time and making it monotonous, so ensure the delete button is displayed beside each task to enable easy clicking and safe removal.
## Thanks and Great Work!

**Comment by PraisesPJMT** [comment]
Thanks so much for the feedback! I just implemented all the recommendations!

Happy Codding!!! :+1:
